services:
  send2ereader:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: send2ereader
    # Restart means, Automatic re-start the container after a shutdown unless manual stop container
    restart: unless-stopped
    # Ports means, Bind external and internal docker ports, only change the external port, not the internal port
    # Format: <External Port>:<Internal Port>
    ports:
      - 3001:3001
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
